### ISSUE TITLE
pi4 UART loopback testing not working with /dev/ttyAMA0

### ISSUE THREAD

**Issue by alvas** [lbrombach/practical_chapters#1]
https://github.com/lbrombach/practical_chapters/blob/6a6ba5ae7b541484cad1e3376845c66e3948ac2b/chapter5/hello_serial.cpp#L21

Actually I need to use /dev/ttyS0 on my pi4.

int UARTHandle = serial_open(pi, "/dev/ttyS0",115200,0);

**Comment by lbrombach** [comment]
Can I ask which Raspberry Pi version and operating system version you are working with?

**Comment by alvas** [comment]
I use raspberry pi 4 B.

➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish

➜  ~ uname -a
Linux qingyun-desktop 5.13.0-1012-raspi #14-Ubuntu SMP PREEMPT Mon Dec 6 15:27:57 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

➜  /etc cat /etc/debian_version
11.0

➜  /etc cat /etc/os-release
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish

➜  ~ cat /proc/cpuinfo
processor       : 0
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2835
Revision        : c03111
Serial          : 10000000e746ca3c
Model           : Raspberry Pi 4 Model B Rev 1.1

**Comment by lbrombach** [comment]
Ah, ok. I have no experience with Ubuntu 21 or even 20 on a Raspberry Pi and thought /dev/ttyS0 was essentially outdated. I guess not all distros have kept up and hopefully your post will help others down the road.
