### ISSUE TITLE
go_to_x [rospack] Error: package 'practical' not found

### ISSUE THREAD

**Issue by alvas** [lbrombach/practical_chapters#2]
Following instruction in chapter 9, 
After compile the node with catkin_make, I run rosrun practical go_to_x, I get the following error:

[rospack] Error: package 'practical' not found.

This is because I have not source the setting to my current shell environment and it can't find the package.

I am using zsh, so I use the following command to set it up:

$source ~/catkin_ws/devel/setup.zsh

After this, I can do rosrun practical go_to_x successfully.

[reference](https://answers.ros.org/question/199940/getting-package-not-found-error/)

**Comment by lbrombach** [comment]
@alvas Can I ask which operating system you are working with and which method you chose to install ROS? The book examples instruct to source .bashrc (pages 150-151 in the paperback), which is in line with the ROS tutorials.

**Comment by alvas** [comment]
First I tried to install ROS on my raspberry pi4 with ubuntu 21.10 impish. But I found out that ROS doesn't support this version yet. So I install ROS neotic in unbuntu 20.04 in my virtualbox VM.

I follow the instructions in http://wiki.ros.org/noetic/Installation/Ubuntu to install noetic. It source setup.zsh from /opt/ros/neotic/setup.zsh to my ~/.zshrc.

After this, I can run rosrun from any folder because rosrun path has been added to my zsh environment.

But When I try "rosrun practical go_to_x" command, I am in ~/catkin_ws/src/ folder. rosrun can't find practical package in my catkin_ws workspace. This is why I need to source ~/catkin_ws/devel/setup.zsh.

I am not sure after catkin_make, how pratical is added to ros environment so rosrun can find it. If you can provide some hint, it would be helpful.

By the way, your book is great. I learn a lot from it. Thanks a lot for your work. I am reading a kindle version.

**Comment by lbrombach** [comment]
Ahh, OK. I haven't had Z Shell yet except on one brand new laptop. I think* you should still have a ~/.bashrc file that could have been used the same for this purpose. But again, hopefully someone finds this useful in the future. And thank you for the kind words, I am very glad that you are enjoying it!
